In [1]:
import numpy as np

In [2]:
from sklearn.preprocessing import MinMaxScaler

In [3]:
data = np.random.randint(0, 100, (10, 2))

In [4]:
data

array([[60, 42],
       [92, 55],
       [ 7, 97],
       [36, 93],
       [11,  8],
       [51, 27],
       [ 0,  2],
       [87, 33],
       [38, 43],
       [57, 22]])

In [5]:
scaler_model = MinMaxScaler()

In [6]:
type(scaler_model)

sklearn.preprocessing.data.MinMaxScaler

In [7]:
scaler_model.fit(data)

/Users/jakkrit/miniconda3/envs/tfdeeplearning/lib/python3.5/site-packages/sklearn/utils/validation.py:444: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

In [8]:
scaler_model.transform(data)

array([[ 0.65217391,  0.42105263],
       [ 1.        ,  0.55789474],
       [ 0.07608696,  1.        ],
       [ 0.39130435,  0.95789474],
       [ 0.11956522,  0.06315789],
       [ 0.55434783,  0.26315789],
       [ 0.        ,  0.        ],
       [ 0.94565217,  0.32631579],
       [ 0.41304348,  0.43157895],
       [ 0.61956522,  0.21052632]])

In [9]:
scaler_model.fit_transform(data)

/Users/jakkrit/miniconda3/envs/tfdeeplearning/lib/python3.5/site-packages/sklearn/utils/validation.py:444: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


array([[ 0.65217391,  0.42105263],
       [ 1.        ,  0.55789474],
       [ 0.07608696,  1.        ],
       [ 0.39130435,  0.95789474],
       [ 0.11956522,  0.06315789],
       [ 0.55434783,  0.26315789],
       [ 0.        ,  0.        ],
       [ 0.94565217,  0.32631579],
       [ 0.41304348,  0.43157895],
       [ 0.61956522,  0.21052632]])

In [12]:
import pandas as pd
data = pd.DataFrame(data=np.random.randint(0, 101, (50, 4)), columns=['f1', 'f2', 'f3', 'label'])

In [13]:
data

f1   f2   f3  label
0    72   13   45     69
1    24   75   25      6
2    44   49   58     20
3    18   82   81     50
4    24    4   54     58
5    16   87   61     94
6     4   37   20      2
7    24   78    8     66
8    41   29   20     80
9    40   29   34     62
10   53   87   85     18
11   77    1   54     87
12    5   67   65     98
13   92   53   33     82
14   51   52   30     62
15   63   57   20     80
16   47   37   74     12
17   46   16    7     81
18   86   20   35     57
19   93   44   96     11
20   34    2   63     54
21   77    7   48     85
22   77   91   63     94
23   78   91   18     87
24   63   16   67      2
25   23   21   41     30
26   10   91   60     97
27   66    2  100     36
28   11   68   51     34
29   50   60   77     26
30   94   42   58     40
31   77   81   36     25
32   10   43    7     72
33   64   48   42     42
34   20   73   81     35
35   94   93   23     62
36  100    0   60     45
37   55  100   87     13
38   71    4   52     84
39   39   71   66     49
40   93   14   69     52
41   36   95   32     23
42   38   29   99     66
43   91   91   85     79
44   45    9    4     71
45   96   70   90     37
46   44   21    9     19
47    9   22   34     89
48   12   45   98      5
49   35   53   60     46

In [14]:
X = data[['f1', 'f2', 'f3']]

In [20]:
y = data['label']

In [21]:
from sklearn.model_selection import train_test_split

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=101)

In [25]:
X_train.shape

(33, 3)

In [26]:
X_train

f1  f2   f3
30   94  42   58
15   63  57   20
20   34   2   63
43   91  91   85
38   71   4   52
44   45   9    4
39   39  71   66
10   53  87   85
49   35  53   60
25   23  21   41
33   64  48   42
36  100   0   60
2    44  49   58
27   66   2  100
34   20  73   81
35   94  93   23
8    41  29   20
19   93  44   96
29   50  60   77
12    5  67   65
5    16  87   61
0    72  13   45
28   11  68   51
4    24   4   54
40   93  14   69
13   92  53   33
9    40  29   34
48   12  45   98
23   78  91   18
6     4  37   20
17   46  16    7
11   77   1   54
31   77  81   36

In [27]:
X_test.shape

(17, 3)

In [28]:
X_test

f1   f2  f3
37  55  100  87
14  51   52  30
21  77    7  48
32  10   43   7
22  77   91  63
1   24   75  25
26  10   91  60
46  44   21   9
42  38   29  99
47   9   22  34
16  47   37  74
24  63   16  67
7   24   78   8
45  96   70  90
18  86   20  35
3   18   82  81
41  36   95  32